import { createSlice, current } from "@reduxjs/toolkit";

const initialState = {
  data: {
    data: [
      {
        merk: "Toyota",
        group_model: "Kijang Inova",
        model: "2.0 E MT",
        year: "2016",
        status: "Bekas",
        KM: "41.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Toyota",
        group_model: "Kijang Inova",
        model: "2.0 G AT",
        year: "2015",
        status: "Bekas",
        KM: "42.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Toyota",
        group_model: "Kijang Inova",
        model: "2.7 V AT",
        year: "2016",
        status: "Bekas",
        KM: "43.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Toyota",
        group_model: "Avanza",
        model: "1.3 E MT",
        year: "2014",
        status: "Bekas",
        KM: "44.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Toyota",
        group_model: "Avanza",
        model: "1.3 G AT",
        year: "2015",
        status: "Bekas",
        KM: "45.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Toyota",
        group_model: "Avanza",
        model: "ALL NEW VELOZ 1.5 AT",
        year: "2018",
        status: "Bekas",
        KM: "46.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Toyota",
        group_model: "Camry",
        model: "2.2 MT",
        year: "2014",
        status: "Bekas",
        KM: "47.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Toyota",
        group_model: "Camry",
        model: "NEW 2.4 G MT",
        year: "2017",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "CR-V",
        model: "ALL NEW 2.4 AT",
        year: "2016",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "CR-V",
        model: "ALL NEW 2.0 AT",
        year: "2017",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "CR-V",
        model: "ALL NEW 1.5 AT TURBO",
        year: "2020",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "BR-V",
        model: "1.5 E AT PRESTIGE",
        year: "2017",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "BR-V",
        model: "1.5 E AT",
        year: "2016",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "BR-V",
        model: "1.5 S MT",
        year: "2018",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "Accord",
        model: "ALL NEW 1.5 TURBO",
        year: "2019",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "Accord",
        model: "ALL NEW 2.4 VTI AT",
        year: "2016",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "Honda",
        group_model: "Accord",
        model: "ALL NEW 2.4 VTI-L AT",
        year: "2017",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "5 Series",
        model: "520i 2.0 AT",
        year: "2014",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "5 Series",
        model: "520i 2.0 AT LUXURY",
        year: "2018",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "5 Series",
        model: "530i G30",
        year: "2021",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "3 Series",
        model: "320i Luxury",
        year: "2015",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "3 Series",
        model: "320i Sport",
        year: "2017",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "3 Series",
        model: "330i M Sport",
        year: "2017",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "7 Series",
        model: "730li 2.0",
        year: "2017",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "7 Series",
        model: "750li F02",
        year: "2010",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
      {
        merk: "BMW",
        group_model: "7 Series",
        model: "740li Executive RSE",
        year: "2012",
        status: "Bekas",
        KM: "48.000",
        location: "Tambora,Jakarta Pusat",
        price: "Rp.250.000.000",
      },
    ],
  },
};

export const carSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    Add_Car: (state) => {
      console.log(current(state));
    },
  },
});

export const { Add_Car } = carSlice.actions;

export const selectCar = (state) => state.user;

export default carSlice.reducer;
