name: scp files
on: [push]
jobs:
  build:
    name: scp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: dumbmerch
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "build"
          target: "/home/dumbmerch"
  build1:
    name: ssh
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: dumbmerch
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/html
            sudo rm -rf testdjubli
            cd /home/dumbmerch
            mv build testdjubli
            sudo mv testdjubli /var/www/html
            sudo service nginx restart
            sudo service nginx status
